# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Sergio Mazzola <smazzola@iis.ee.ethz.ch>

name: lint

on: [ push, workflow_dispatch ]

jobs:

  lint-license:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Check license
      uses: pulp-platform/pulp-actions/lint-license@v2
      with:
        license: |
          Copyright (\d{4}(-\d{4})?\s)?.*
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
        exclude_paths: |
          utils/*
          sw/include/regs/*
          scripts/run_clang_format.py


  lint-sv:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Run Verible
      uses: chipsalliance/verible-linter-action@main
      with:
        paths: hw
        extra_args: "--waiver_files .github/verible.waiver"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_error: true
        reviewdog_reporter: github-check
        exclude_paths: hw/rdl

  lint-sv-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Verible formatter action
        uses: chipsalliance/verible-formatter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files:
            ./hw/*.sv
            ./target/sim/src/*.sv
          parameters:
            --flagfile .verilog_format
          fail_on_formatting_suggestions: true

  lint-cxx:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Run Clang-format
      uses: DoozyX/clang-format-lint-action@v0.14
      with:
        extensions: 'c,h,cpp'
        clangFormatVersion: 12
        style: >
          {
          IndentWidth: 4,
          ColumnLimit: 100,
          AlignEscapedNewlines: DontAlign,
          SortIncludes: false,
          AllowShortFunctionsOnASingleLine: None,
          AllowShortIfStatementsOnASingleLine: true,
          AllowShortLoopsOnASingleLine: true
          }
        exclude: |
          ./sw/include/regs/*.h
